menus:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  archives: /archives/ || fa fa-archive
menus-config:
  enable-icon: true

avatar:
  url: /images/tiger400.jpg

site-state: true

social:
  GitHub: https://github.com/w4ngzhen || fa fa-github
  RSS: /atom.xml || fa fa-rss

favicon:
  small: /images/compilemind_16x16.png
  medium: /images/compilemind_32x32.png
  apple_touch_icon: /images/compilemind_32x32.png
  safari_pinned_tab: /images/compilemind_32x32.png